### ISSUE TITLE
Should this work consistently with Meteor 1.2

### ISSUE THREAD

**Issue by sferoze** [martijnwalraven/meteor-ios#67]
I am getting reports from a team member working with this DDP package that the connection seems unstable. I am unable to pinpoint what it is. It is stable when he connects to a previous build on Meteor 1.1 and node 0.10.36. The new server has Meteor 1.2 and node 0.10.4.

It should work the same on both version right? Could this be a DDP thing?

**Comment by sferoze** [comment]
It seems to keep disconnecting when we try to connect:

```
2015-09-25 00:33:22.115 App[14853:2750531] Will retry opening connection after 12.624253 seconds
2015-09-25 00:33:34.744 App[14853:2752524] Connecting to DDP server at URL: http://li1261-xxx.members.linode.com/websocket
2015-09-25 00:33:35.761 App[14853:2750531] Connected to DDP server with protocol version: 1, sessionID: koKD6FGdbyEX3Cp3v
2015-09-25 00:33:36.172 App[14853:2750531] Will retry opening connection after 17.624845 seconds

2015-09-25 00:33:53.797 App[14853:2753773] Connecting to DDP server at URL: http://li1261-xxx.members.linode.com/websocket
2015-09-25 00:33:55.220 App[14853:2750531] Connected to DDP server with protocol version: 1, sessionID: ABnubFe2nNRZhtJFR
2015-09-25 00:33:55.287 App[14853:2750531] Will retry opening connection after 43.482757 seconds
```

**Comment by martijnwalraven** [comment]
Hmm, I'll look into this!

**Comment by sferoze** [comment]
@martijnwalraven thanks. If you cannot reproduce with a Meteor 1.2 app and node 0.10.4 then it must be my deployment or something.

**Comment by sferoze** [comment]
It is able to connect for short periods. It is sorta working but just isn't stable. It keeps dropping the connection.

**Comment by martijnwalraven** [comment]
I haven't been able to reproduce this with the leaderboard app running on Meteor 1.2 and deployed to *.meteor.com. So I suspect it indeed has to do with your deployment. 

Found this [stackoverflow question](http://stackoverflow.com/questions/23404160/why-does-my-wss-websockets-over-ssl-tls-connection-immediately-disconnect-w) that seems kind of similar. But from your output it seems you're not using SSL?

**Comment by martijnwalraven** [comment]
Oh, just read your last answer. If it is able to connect for short periods, it is unlikely to be the certificate. But not using SSL might actually be the problem, especially if there could be some kind of proxy in between (common when using cellular networks). Was the Meteor 1.1 app using SSL?

**Comment by sferoze** [comment]
no SSL with the Meteor 1.1 server either. 

Could using or not using OPLOG make any difference?

**Comment by mathieutozer** [comment]
I'm experiencing this too after upgrading to 1.2. The only interesting thing that I can see in the errors is from PSWebSocket reporting 'Failed to inflate bytes'.

**Comment by sferoze** [comment]
Yes I can confirm this package is an issue with Meteor 1.2

I downgraded our new server to Meteor 1.1 and everything is stable like it was.

Meteor 1.2 has introduced web socket compression and I think that has to do with this issue.

**Comment by mathieutozer** [comment]
Do you mind telling me how to roll back? All I can find with google is for
really old versions.
2015年9月25日(金) 10:59 Feroze Shahpurwala <notifications@github.com>:

**Comment by sferoze** [comment]
@mathieutozer Are you using version control?

It's quite simple with Meteor.

1) Clone your entire repo into a new folder
2) Git reset your repo to a commit that was prior to 1.2
3) Then replace all the content in your root folder (expect hidden .meteor folder), with the contents from your current Meteor 1.2 root directory. This will make it so you have your latest code running on Meteor 1.1

**Comment by martijnwalraven** [comment]
@sferoze Ah, good point about the web socket compression!

I should have tested with the current released version of Meteor iOS, but I have been working on updating the project to Xcode 7. As part of that I also upgraded the PocketSocket dependency, and that fixes the web socket compression issue. So that's why I couldn't reproduce the issue.

I pushed the commit with the changes to master, but it's not ready to be released yet. Still figuring out Carthage compatibility and some Swift 2 / iOS 9 issues with the Todos example.

But if you're using CocoaPods you should be able to test the new version using:
```ruby
pod 'Meteor', git: 'https://github.com/martijnwalraven/meteor-ios'
```

**Comment by mathieutozer** [comment]
So I'm still trying to resolve this. I am working with a fork for OS X which I've bought up to date with master, but PocketSocket is still failing. 

The preview merge of the two looks like this https://github.com/martijnwalraven/meteor-ios/compare/master...mathieutozer:master
The interesting stuff is down the bottom (need to rebuild the OS X examples, so ignore that for now), some ifdefs to cut out iOS only lines, and it could be some thing weird going on with that but it was working fine up until I updated my meteor code to 1.2.

**Comment by mathieutozer** [comment]
I've simply turned off seb socket compression for now by launching meteor with

`SERVER_WEBSOCKET_COMPRESSION=0 meteor`

I'm no where near needing to release anything publicly product wise so just unblocking development is OK with me!

**Comment by agao** [comment]
@martijnwalraven After using pod 'Meteor', git: 'https://github.com/martijnwalraven/meteor-ios'
I'm getting the same error as below:

You can reproduce this by connecting the todo example to testtodoslist.meteor.com which is a stock meteor example.

2015-10-11 20:36:45.728 Todos[10084:494674] Connected to DDP server with protocol version: 1, sessionID: T5e9peykufjmeajMK
2015-10-11 20:36:46.036 Todos[10084:494674] Will retry opening connection after 0.100000 seconds
2015-10-11 20:36:46.138 Todos[10084:494715] Connecting to DDP server at URL: wss://testtodoslist.meteor.com/websocket
2015-10-11 20:36:46.139 Todos[10084:494715] PSWebSocket: debug mode allowing all SSL certificates
2015-10-11 20:36:48.799 Todos[10084:494674] Connected to DDP server with protocol version: 1, sessionID: GTXmSdvzkBS5NkAdC
2015-10-11 20:36:49.108 Todos[10084:494674] Will retry opening connection after 0.100000 seconds
2015-10-11 20:36:49.214 Todos[10084:494825] Connecting to DDP server at URL: wss://testtodoslist.meteor.com/websocket
2015-10-11 20:36:49.215 Todos[10084:494825] PSWebSocket: debug mode allowing all SSL certificates
2015-10-11 20:36:51.872 Todos[10084:494674] Connected to DDP server with protocol version: 1, sessionID: jg3DWiAF5LnMAjm7R
2015-10-11 20:36:52.180 Todos[10084:494674] Will retry opening connection after 5.734486 seconds
2015-10-11 20:36:57.916 Todos[10084:494826] Connecting to DDP server at URL: wss://testtodoslist.meteor.com/websocket
2015-10-11 20:36:57.917 Todos[10084:494826] PSWebSocket: debug mode allowing all SSL certificates
2015-10-11 20:37:00.784 Todos[10084:494674] Connected to DDP server with protocol version: 1, sessionID: WW6YvQry44PLYj4Jw
2015-10-11 20:37:01.060 Todos[10084:494674] Will retry opening connection after 11.942520 seconds
2015-10-11 20:37:13.004 Todos[10084:494715] Connecting to DDP server at URL: wss://testtodoslist.meteor.com/websocket
2015-10-11 20:37:13.005 Todos[10084:494715] PSWebSocket: debug mode allowing all SSL certificates
2015-10-11 20:37:15.837 Todos[10084:494674] Connected to DDP server with protocol version: 1, sessionID: RF2atZMzfDDqzgbP2
2015-10-11 20:37:16.144 Todos[10084:494674] Will retry opening connection after 21.173734 seconds

**Comment by calioasis** [comment]
Same problem for me, with using pod 'Meteor', git: 'https://github.com/martijnwalraven/meteor-ios'

Please help!

**Comment by karlml** [comment]
I have the same problem with a Meteor 1.2 webapp, and an "empty" Xcode project (iOS9 and swift 2.0), all we do is install the pod, import framework, add 
let Meteor = METDDPClient(serverURL: NSURL(string: "http://xxx.xxx.xxx/websocket")!) and Meteor.connect() in AppDelegate.  I have pasted in the console output below.  What is the best workaround for this, except downgrading to Meteor 1.1 ?  It was mentioned by @mathieutozer that we could launch Meteor with SERVER_WEBSOCKET_COMPRESSION=0 meteor.  How is that done?   Did it work?   Any help with resolving this would be great !


2015-10-26 18:58:43.002 XXXTest[287:19025] Connecting to DDP server at URL: http://XXX.XXX.XXX/websocket
2015-10-26 18:58:43.555 XXXTest[287:18974] Connected to DDP server with protocol version: 1, sessionID: jNWpiMnLstiAy7oeS
2015-10-26 18:58:43.608 XXXTest[287:18974] Will retry opening connection after 0.100000 seconds
2015-10-26 18:58:43.710 XXXTest[287:19004] Connecting to DDP server at URL: http://XXX.XXX.XXX/websocket

...etc

**Comment by karlml** [comment]
For people that come across this issue launching Meteor as mentioned by @mathieutozer works

SERVER_WEBSOCKET_COMPRESSION=0 **meteor**

**Comment by calioasis** [comment]
Instead of running 'meteor' in Terminal, run 'SERVER_WEBSOCKET_COMPRESSION=0 meteor'

**Comment by yesitsdave** [comment]
I'm seeing this same problem with the latest from github.
The exact error seems to be Z_DATA_ERROR from zlib inflate in PSWebSocketInflater.m line 68.

Here's a quick and dirty workaround if you are unable or unwilling to disable compression server side - 
Edit Vendor/PocketSocket/PocketSocket/PSWebSocketDriver.m and change line 113 to:
`_pmdEnabled = NO;`

This should work by disabling the compression in pocketsocket.

**Comment by sferoze** [comment]
@martijnwalraven what do you think of @yesitsdave solution? We tested it and it seems to work. I really want to update production to Meteor 1.2 and we are thinking of using @yesitsdave fix he mentioned above. What do you think?

**Comment by martijnwalraven** [comment]
As far as I know, there is no danger in disabling WebSocket compression, although it might give you slightly worse performance (the same as before Meteor 1.2 though).

I'm wondering why using the current master version of Meteor iOS doesn't work however, because I updated the PocketSocket dependency and was able to connect successfully to an app running on Meteor 1.2. I haven't had time to test this again, but it's definitely on my mind.

**Comment by sferoze** [comment]
@martijnwalraven How long did you test for? Because when I was testing sometimes I thought it was working but after using it more I noticed it start to fail. Then next time I logged in it failed immediately. 

Basically after a short test I thought it was working too. If you try to do some actions like call a method or use the app, it should start to fail.

**Comment by yesitsdave** [comment]
@martijnwalraven the issue doesn't appear on every ddp message, I could log in fine and retrieve some documents, but others would show the error. Meteor-ios is awesome BTW :)

**Comment by martijnwalraven** [comment]
Hmmm, I know it failed immediately before I updated PocketSocket, and it worked afterward. I used Todos and I think I did add some items, but I haven't tested it extensively. Intermittent failures would suggest there is some incompatibility between the Meteor and PocketSocket implementations of compression, weird. Disabling WebSocket compression is probably the best workaround for now.

**Comment by agao** [comment]
@martijnwalraven  I also want to say Meteor-ios is awesome. The problem shows easily when you add a lot of items to the todo list very quickly or when you slowly add 20+ items. Will use the workaround for now.

**Comment by Romerio** [comment]
Thanxs @mathieutozer

**Comment by Ben305** [comment]
I'm running into the same problem, has anyone been able to investigate the problem further?

**Comment by karlml** [comment]
The two workarounds suggested in this thread work. 

1) SERVER_WEBSOCKET_COMPRESSION=0 meteor

and 

2) "Here's a quick and dirty workaround if you are unable or unwilling to disable compression server side - 
Edit Vendor/PocketSocket/PocketSocket/PSWebSocketDriver.m and change line 113 to:
_pmdEnabled = NO;"

**Comment by Ben305** [comment]
@karlml: Thanks, but I was hoping that somebody found the root cause for this problem.

**Comment by seviu** [comment]
The problem is happening on PocketSocket while unzipping. I found that the fix explained in this stackoverflow works:
http://stackoverflow.com/questions/18700656/zlib-inflate-failing-with-3-z-data-error

Inflate() was failing because it was looking for GZip headers which were not present. If you initialize the stream with:

ret = inflateInit2(&strm, -MAX_WBITS);
Passing a negative window bits value prevents inflate from checking for gzip or zlib headers and unzipping works as expected.

**Comment by seviu** [comment]
Another solution is to start using the development branch of PocketSocket, just add it to your Podfile
pod 'PocketSocket', :git => 'https://github.com/zwopple/PocketSocket.git', :branch => 'develop'

**Comment by karlml** [comment]
Thanks for update!  What are the performance impact of the compression in your opinion? When should we start to worry ? Is there a significant improvement?

**Comment by seviu** [comment]
By using the development branch of PocketSocket or by using the pull request I submitted, compression should still be working fine. No need to disable it at all.

**Comment by robertjpayne** [comment]
@karlml in general permessage-deflate compression is going to be well worth it for any mobile app as your more constrained on network speeds than you are on CPU speed.

It's very configurable on the server end ( how much compression happens ) so I wouldn't worry about performance implications.

**Comment by robertjpayne** [comment]
Also to anyone following this, PocketSocket had a bad bug in the permessage-deflate implementation I never caught. I've got a fix ( just running all new Autobahn tests to ensure ) and a new release will be out on Cocoapods by tomorrow hopefully so you can leave compression on!

**Comment by robertjpayne** [comment]
@martijnwalraven strongly recommend you upgrade this repo to use PocketSocket 1.0.0 as it contains the critical fixes for permessage-deflate support.

**Comment by karlml** [comment]
@robertjpayne @martijnwalraven  I am occasionally getting a crash when the app is brought from the background into the foreground..  I am wondering if it something I am doing wrong or if this is a related issue ?
![screen shot 2016-03-31 at 23 14 51](https://cloud.githubusercontent.com/assets/9771583/14191092/6f5026d6-f796-11e5-9565-8bab489b4547.png)

**Comment by martijnwalraven** [comment]
@robertjpayne: Thanks for fixing the `permessage-deflate` bug in PocketSocket! I've updated the repository and pushed a new CocoaPods release.

**Comment by ShikharQuovantis** [comment]
I have downloaded the Latest code from your repository and still the "Todos" app is giving the same error of establishing the connection again and again.
Here is the Xcode console output:-
Connecting to DDP server at URL: wss://medcircle-staging.mod.bz/websocket
2016-04-11 18:19:52.892 Todos[576:223385] Will retry opening connection after 0.100000 seconds
2016-04-11 18:19:52.995 Todos[576:223436] Connecting to DDP server at URL: wss://medcircle-staging.mod.bz/websocket
2016-04-11 18:19:54.428 Todos[576:223385] Will retry opening connection after 0.100000 seconds
2016-04-11 18:19:54.531 Todos[576:223436] Connecting to DDP server at URL: wss://medcircle-staging.mod.bz/websocket

this is my own server url which is working fine completely as I have checked it with ObjectiveDDP client. But since your library has immense support for coredata, I want to stick it to that only. Please help in getting past this error.

**Comment by karlml** [comment]
Have you tried to connect like this?

let Meteor = METDDPClient(serverURL: NSURL(string: "https://myappsecure.com/websocket")!)
let Meteor = METDDPClient(serverURL: NSURL(string: "http://myapp.com/websocket")!)

**Comment by ShikharQuovantis** [comment]
@karlml:-
This is exact string which I have used:-
let Meteor = METCoreDataDDPClient(serverURL: NSURL(string: "wss://medcircle-staging.mod.bz/websocket")!)

is this is creating the issue? Why did you mention it two times?

**Comment by karlml** [comment]
@ShikharQuovantis hmm, tried with wss now on the old git and worked so guess maybe there is still something wrong and you have to deploy without websocket compression

**Comment by ShikharQuovantis** [comment]
Does this mean that the bug in the current version of Meteor still persists? 

How can I use the old git from just the iOS side?

**Comment by ShikharQuovantis** [comment]
We have deployed meteor application on modulus.io, how can we deploy there without websocket compression?

**Comment by ShikharQuovantis** [comment]
@martijnwalraven Please bail me out for this scenario. It is still happening with me, I am not able to use it  as it is not able to connect to the server.

**Comment by karlml** [comment]
@ShikharQuovantis Try perhaps and post it on the Meteor Forum, Martin works for the MDG

**Comment by yesitsdave** [comment]
@ShikharQuovantis I think you may be having an issue with the new PocketSocket and SSL support. Here is a quick workaround you can try: 

Edit Vendor/PocketSocket/PocketSocket/PSWebSocket.m and change line 282 to:
`_negotiatedSSL = YES;`

**Comment by yesitsdave** [comment]
This issue has been fixed in the latest PocketSocket 1.01.

**Comment by black-lotus** [comment]
I am facing same issues.
Our server using Meteor 1.4 and always trigger "Will retry opening connection" message after 18 seconds :(

these are the full logs

```
Will retry opening connection after 0.100000 seconds
Connecting to DDP server at URL: https://xxxxxxxxxxx
 Connected to DDP server with protocol version: 1, sessionID: SzNJhCB7ks5ES3AWA

didFailWithError Error Domain=PSWebSocketErrorDomain Code=3 "Output stream end encountered" UserInfo={NSLocalizedDescription=Output stream end encountered}
Will retry opening connection after 4.262444 seconds

```
Any help would be appreciated
